pipeline:
  agent: any

  environment:
    DOCKER_IMAGE: "api_test_automation"

  stages:
    - stage: "Build Docker Image"
      steps:
        - echo: 'Building the Docker image...'
        - script:
            sh: "docker build -t ${DOCKER_IMAGE} ."

    - stage: "Run Tests in Docker"
      steps:
        - echo: 'Running tests inside Docker container...'
        - script:
            sh: "docker run --rm -v '${WORKSPACE}/allure-results:/usr/src/app/allure-results' ${DOCKER_IMAGE}"

  post:
    always:
      steps:
        - echo: 'Cleaning up Docker resources...'
        - script:
            sh: "docker rmi ${DOCKER_IMAGE} || true"

        - echo: 'Publishing Allure reports...'
        - allure:
            includeProperties: false
            jdk: ''
            results:
              - path: "allure-results"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - approval:
          type: approval
          requires:
            - build
      - test:
          requires:
            - approval