version: 2.1

jobs:
  build_docker_image:
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            echo "Building the Docker image..."
            docker build -t web_test_automation .

  run_tests_in_docker:
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Run Tests in Docker Container
          command: |
            echo "Running tests inside Docker container..."
            docker run --rm web_test_automation

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_docker_image
      - run_tests_in_docker:
          requires:
            - build_docker_image
