version: 2.1

executors:
  java-executor:
    docker:
      - image: openjdk:21-jdk  # Use official OpenJDK image for JDK 21
    working_directory: ~/project

jobs:
  test:
    executor: java-executor
    steps:
      - checkout  # Check out the repository code

      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      - run:
          name: Install dependencies
          command: mvn install -DskipTests

      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

      - run:
          name: Run tests
          command: mvn test
