version: 2.1

executors:
  java-executor:
    docker:
      - image: openjdk:21-jdk  # Use official OpenJDK image for JDK 21
    working_directory: ~/project

jobs:
  test:
    executor: java-executor
    steps:
      - checkout

      - run:
          name: Set up Maven cache
          command: |
            mkdir -p ~/.m2
            echo '<settings><profiles><profile><id>no-snapshot-updates</id><activation><activeByDefault>true</activeByDefault></activation><repositories><repository><id>central</id><url>https://repo.maven.apache.org/maven2</url><snapshots><enabled>false</enabled></snapshots></repository></repositories></profile></profiles></settings>' > ~/.m2/settings.xml

      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      - run:
          name: Install dependencies
          command: mvn install -DskipTests

      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

      - run:
          name: Run tests
          command: mvn test
