version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:20.10.7  # Use Docker image with Docker installed
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build -t my_maven_app .
      - run:
          name: Run Tests
          command: |
            docker run --rm my_maven_app

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
